FROM maven:3.9.6-eclipse-temurin-21-alpine as builder
WORKDIR /gsearch
COPY pom.xml .
RUN mvn -e -B dependency:resolve
COPY src ./src
RUN mvn -e -B package -DskipTests

FROM eclipse-temurin:21.0.1_12-jdk-jammy
COPY --from=builder /gsearch/target/gsearch.jar ./gsearch.jar
ENTRYPOINT java -jar gsearch.jar
