FROM maven:3.8.5-openjdk-17-slim as builder
WORKDIR /gsearch
COPY pom.xml .
RUN mvn -e -B dependency:resolve
COPY src ./src
RUN mvn -e -B package -DskipTests

FROM openjdk:17.0.1-jdk-slim-bullseye
COPY --from=builder /gsearch/target/gsearch.jar ./gsearch.jar
ENTRYPOINT java -jar gsearch.jar
