FROM maven:3.9.5-eclipse-temurin-21-alpine

RUN apk upgrade --available --no-cache

WORKDIR /gsearch

COPY pom.xml .

RUN mvn -e -B dependency:resolve

COPY src ./src

RUN mvn -e -B package -DskipTests